Letterbadd/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('badboxd.urls')),

]

badboxd/urls.py
from django.urls import path
from badboxd.views import emp, show, edit, update, destroy


urlpatterns = [
    path('emp', emp),
    path('show/', show),
    path('edit/<int:id>', edit,name = "edit"),
    path('update/<int:id>', update,name = "update"),
    path('delete/<int:id>', destroy, name = "delete"),



]

badboxd/models.py
from django.db import models


# Create your models here.

RatingChoices = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),

]

class FavoriteMovies(models.Model):
    name = models.CharField(max_length=168, blank=True, null=True)
    watchedDate = models.DateField()
    rating = models.IntegerField(blank=True, null= True, choices= RatingChoices)

    class Meta:
        db_table = "FMovies"

badboxd/forms.py
from django.forms import ModelForm
from badboxd.models import FavoriteMovies



class FMoviesForms(ModelForm):
    class Meta:
        model = FavoriteMovies
        fields = ['name', 'watchedDate', 'rating']

badboxd/views.py
from django.shortcuts import render, redirect
from badboxd.models import FavoriteMovies
from badboxd.forms import FMoviesForms


# Create your views here.
def emp(request):
    if request.method == "POST":
        form = FMoviesForms(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show/')
            except:
                pass
    else:
        form = FMoviesForms()
    return render(request, 'index.html', {'form': form})


def show(request):
    fmovies=FavoriteMovies.objects.all()
    return render(request, "show.html", {'fmovies': fmovies})


def edit(request, id):
    fmovie = FavoriteMovies.objects.get(id=id)
    return render(request, 'edit.html', {'fmovie': fmovie})


def update(request, id):
    fmovie = FavoriteMovies.objects.get(id=id)
    form = FMoviesForms(request.POST, instance=fmovie)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'fmovie': fmovie})


def destroy(request, id):
    fmovie = FavoriteMovies.objects.get(id=id)
    fmovie.delete()
    return redirect("/show")

templates/edit.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Badboxd</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/atualizar/{{fmovie.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Atualize os dados</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nome do Filme:</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_name" required maxlength="20" value="{{ fmovie.name }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Data que assistiu:</label>
    <div class="col-sm-4">
        <input type="text" name="watchedDate" id="id_watchedDate" required maxlength="100" value="{{ fmovie.watchedDate }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nota:</label>
    <div class="col-sm-4">
        <input type="number" name="rating" id="id_rating" required maxlength="254" value="{{ fmovie.rating }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Atualizar</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Badboxd</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Preencha com seu filme favorito</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"> Nome do Filme:</label>
    <div class="col-sm-4">
      {{ form.name }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Data que assistiu:</label>
    <div class="col-sm-4">
      {{ form.watchedDate }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nota:</label>
    <div class="col-sm-4">
      {{ form.rating }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

templates/show.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Lista dos Filmes</title>
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Nome do Filme</th>
        <th>Data que assistiu</th>
        <th>Nota</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
{% for fmovie in fmovies %}
    <tr>
        <td>{{ fmovie.name }}</td>
        <td>{{ fmovie.watchedDate }}</td>
        <td>{{ fmovie.rating }}</td>
        <td>
            <a href="/edit/{{ fmovie.id }}"><span class="glyphicon glyphicon-pencil" >Editar</span></a>
            <a href="/delete/{{ fmovie.id }}">Deletar</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<div style="text-align: center;"><a href="/emp" class="btn btn-primary">Adicionar um novo Filme</a></div>
</body>
</html>